'use client';
import {useMemo,useState} from 'react';
import {dailyMeals,saladRecipes,Recipe} from '@/lib/mealPlan';

const img=(src:string)=>src;
function Nutrition({r}:{r:Recipe}){return <div className="nutrition"><span>🔥 {r.calories} kcal</span><span>💪 {r.protein}g P</span><span>🥔 {r.carbs}g C</span><span>🥑 {r.fat}g F</span><span>🌿 {r.fiber}g fiber</span></div>}
function RecipeDetail({r,onBack}:{r:Recipe,onBack:()=>void}){return <div className="detail"><button className="back" onClick={onBack}>← Back</button><img className="hero" src={img(r.image)} alt={r.name}/><div className="detailHead"><div><div className="eyebrow">{r.category} · {r.time}</div><h1>{r.name}</h1></div><button className="heart">♡</button></div><Nutrition r={r}/><section><h2>Ingredients</h2><ul className="ingredients">{r.ingredients.map((x,i)=><li key={i}>✓ <span>{x}</span></li>)}</ul></section><section><h2>How to prepare</h2><ol className="steps">{r.steps.map((x,i)=><li key={i}><b>Step {i+1}</b><span>{x}</span></li>)}</ol></section>{r.tip&&<div className="tip"><b>💡 Preparation tip</b><p>{r.tip}</p></div>}</div>}
function SaladCard({r,onClick}:{r:Recipe,onClick:()=>void}){return <button className="recipeCard" onClick={onClick}><img src={r.image} alt=""/><div className="recipeBody"><div className="eyebrow">SALAD · {r.time}</div><h3>{r.name}</h3><Nutrition r={r}/><span className="view">View full recipe →</span></div></button>}
export default function Home(){
 const [tab,setTab]=useState('today'); const [selected,setSelected]=useState<Recipe|null>(null); const [search,setSearch]=useState('');
 const filtered=useMemo(()=>saladRecipes.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())),[search]);
 if(selected) return <main><RecipeDetail r={selected} onBack={()=>setSelected(null)}/></main>;
 return <main><header className="top"><div><div className="brand">🥗 NutriPlan</div><p>Your daily nutrition companion</p></div><button className="icon">🔔</button></header>
 <section className="welcome"><div><span className="eyebrow">TODAY · TUESDAY, 29 SEPTEMBER 2026</span><h1>Good morning 👋</h1><p>Plan every meal, cook with confidence and keep your nutrition organized.</p></div><div className="target"><b>Today's targets</b><strong>1,850 kcal</strong><small>Protein 135g · Fiber 30g</small></div></section>
 <div className="quick"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}>🍽️ Today</button><button className={tab==='salads'?'active':''} onClick={()=>setTab('salads')}>🥗 Salads</button><button onClick={()=>setTab('recipes')}>📖 Recipes</button><button onClick={()=>setTab('shopping')}>🛒 Shopping</button></div>
 {tab==='salads'?<section className="panel"><div className="sectionHead"><div><span className="eyebrow">SALAD LIBRARY</span><h2>Healthy salad recipes</h2><p>International salads with exact ingredients and step-by-step preparation.</p></div></div><input className="search" placeholder="Search salads..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="grid">{filtered.map(r=><SaladCard key={r.id} r={r} onClick={()=>setSelected(r)}/>)}</div></section>:tab==='recipes'?<section className="panel"><div className="sectionHead"><div><span className="eyebrow">RECIPE LIBRARY</span><h2>Salads are included as a full recipe category</h2><p>Tap any salad to see ingredients, quantities and preparation steps.</p></div></div><div className="grid">{saladRecipes.map(r=><SaladCard key={r.id} r={r} onClick={()=>setSelected(r)}/>)}</div></section>:tab==='shopping'?<section className="panel"><span className="eyebrow">THIS WEEK</span><h2>Shopping list</h2><div className="shopping"><b>🥬 Salad vegetables</b><p>Cucumber · tomato · lettuce · spinach · cabbage · peppers · onions · herbs</p><b>🍋 Salad dressing</b><p>Lemon/lime · olive oil · sumac · oregano · cumin · sesame oil</p><b>🥜 Nuts & seeds</b><p>Almonds · walnuts · cashews · pistachios · sunflower seeds · chia</p></div></section>:<section className="panel"><div className="sectionHead"><div><span className="eyebrow">TODAY'S MEALS</span><h2>Tuesday meal timeline</h2></div></div>{['Curd + berries + seeds','Avocado Nuts Shake','Salmon + lentils + Greek Salad','Apple + walnuts','White Fish + vegetables'].map((m,i)=><div className="meal" key={m}><img src={i===2?saladRecipes[1].image:saladRecipes[0].image} alt=""/><div><span className="eyebrow">{['BREAKFAST','MID-MORNING','LUNCH','EVENING SNACK','DINNER'][i]}</span><h3>{m}</h3><p>{i===2?'Includes the detailed Greek Salad recipe →':'Tap for recipe and ingredients'}</p></div><span className="arrow">→</span></div>)}<div className="saladCallout"><div className="emoji">🥗</div><div><b>Need a salad?</b><p>Open the Salads menu for 7 detailed recipes including Mediterranean, Greek, Mexican, Turkish, Lebanese, Thai and Tuna salads.</p></div><button onClick={()=>setTab('salads')}>Open Salads</button></div></section>}
 <nav><button className={tab==='today'?'navActive':''} onClick={()=>setTab('today')}>⌂<span>Today</span></button><button onClick={()=>setTab('recipes')}>▦<span>Plan</span></button><button onClick={()=>setTab('salads')} className={tab==='salads'?'navActive':''}>🥗<span>Salads</span></button><button onClick={()=>setTab('shopping')} className={tab==='shopping'?'navActive':''}>🛒<span>Shopping</span></button><button onClick={()=>setTab('today')}>☺<span>Profile</span></button></nav>
 </main>
}
