'use client';
import {useMemo,useState} from 'react';
import {dailyMeals,saladRecipes,Recipe} from '@/lib/mealPlan';

function Nutrition({r}:{r:Recipe}){return <div className="nutrition"><span>🔥 {r.calories} kcal</span><span>💪 {r.protein}g P</span><span>🥔 {r.carbs}g C</span><span>🥑 {r.fat}g F</span><span>🌿 {r.fiber}g fiber</span></div>}
function RecipeDetail({r,onBack}:{r:Recipe,onBack:()=>void}){return <div className="detail"><button className="back" onClick={onBack}>← Back</button><img className="hero" src={r.image} alt={r.name}/><div className="detailHead"><div><div className="eyebrow">{r.category} · {r.time}</div><h1>{r.name}</h1></div><button className="heart">♡</button></div><Nutrition r={r}/><section><h2>Ingredients</h2><ul className="ingredients">{r.ingredients.map((x,i)=><li key={i}>✓ <span>{x}</span></li>)}</ul></section><section><h2>How to prepare</h2><ol className="steps">{r.steps.map((x,i)=><li key={i}><b>Step {i+1}</b><span>{x}</span></li>)}</ol></section>{r.tip&&<div className="tip"><b>💡 Preparation tip</b><p>{r.tip}</p></div>}</div>}
function SaladCard({r,onClick}:{r:Recipe,onClick:()=>void}){return <button className="recipeCard" onClick={onClick}><img src={r.image} alt=""/><div className="recipeBody"><div className="eyebrow">SALAD · {r.time}</div><h3>{r.name}</h3><Nutrition r={r}/><span className="view">View full recipe →</span></div></button>}
function TelegramPanel(){
 const [status,setStatus]=useState<any>(null); const [result,setResult]=useState<any>(null); const [loading,setLoading]=useState(false);
 async function call(path:string){setLoading(true);setResult(null);try{const r=await fetch(path);const d=await r.json();setResult(d)}catch(e){setResult({ok:false,error:'Request failed'})}finally{setLoading(false)}}
 return <section className="panel"><div className="sectionHead"><div><span className="eyebrow">INTEGRATION</span><h2>Telegram notifications</h2><p>Verify the bot, discover your chat ID and send a live test message.</p></div></div><div className="telegramBox"><div><b>1. Send /start to your NutriPlan bot</b><p>This creates a Telegram update that NutriPlan can detect.</p></div><button onClick={()=>call('/api/telegram/discover-chat')}>{loading?'Checking…':'🔎 Discover chat ID'}</button><div><b>2. Verify configuration</b><p>Checks the bot token and configured chat ID without exposing secrets.</p></div><button onClick={()=>call('/api/telegram/status')}>{loading?'Checking…':'✅ Check Telegram'}</button><div><b>3. Send a live message</b><p>After TELEGRAM_CHAT_ID is saved in Vercel, this sends a real notification.</p></div><button onClick={()=>call('/api/test-telegram')}>{loading?'Sending…':'📨 Send test message'}</button></div>{result&&<pre className="result">{JSON.stringify(result,null,2)}</pre>}<p className="muted">If a chat ID is discovered, copy it into Vercel → Settings → Environment Variables as <b>TELEGRAM_CHAT_ID</b>, then redeploy.</p>{status&&<pre>{JSON.stringify(status,null,2)}</pre>}</section>
}
export default function Home(){
 const [tab,setTab]=useState('today'); const [selected,setSelected]=useState<Recipe|null>(null); const [search,setSearch]=useState('');
 const filtered=useMemo(()=>saladRecipes.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())),[search]);
 if(selected) return <main><RecipeDetail r={selected} onBack={()=>setSelected(null)}/></main>;
 const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
 return <main><header className="top"><div><div className="brand">🥗 NutriPlan</div><p>Your daily nutrition companion</p></div><button className="icon">🔔</button></header>
 <section className="welcome"><div><span className="eyebrow">TODAY · {new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</span><h1>Good morning 👋</h1><p>Plan meals, follow complete recipes and keep your shopping organized.</p></div><div className="target"><b>Today's targets</b><strong>1,850 kcal</strong><small>Protein 135g · Fiber 30g</small></div></section>
 <div className="quick"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}>🍽️ Today</button><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}>📅 Weekly Plan</button><button className={tab==='salads'?'active':''} onClick={()=>setTab('salads')}>🥗 Salads</button><button className={tab==='shopping'?'active':''} onClick={()=>setTab('shopping')}>🛒 Shopping</button><button className={tab==='telegram'?'active':''} onClick={()=>setTab('telegram')}>✈️ Telegram</button></div>
 {tab==='salads'?<section className="panel"><div className="sectionHead"><div><span className="eyebrow">SALAD LIBRARY</span><h2>Healthy salad recipes</h2><p>Seven international salads with exact ingredients and preparation.</p></div></div><input className="search" placeholder="Search salads..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="grid">{filtered.map(r=><SaladCard key={r.id} r={r} onClick={()=>setSelected(r)}/>)}</div></section>
 :tab==='plan'?<section className="panel"><span className="eyebrow">7-DAY PLAN</span><h2>Weekly meal plan</h2><div className="weekGrid">{days.map((d,i)=><button key={d} className="dayCard" onClick={()=>setTab('today')}><b>{d}</b><span>{i===1?'Salmon + lentils + Greek Salad':i===3?'Chicken liver + chicken + Turkish Salad':i===6?'Tuna + chicken + Mediterranean Salad':'Protein + vegetables + controlled carbs'}</span><small>Breakfast · Lunch · Dinner</small></button>)}</div></section>
 :tab==='shopping'?<section className="panel"><span className="eyebrow">AUTO SHOPPING</span><h2>Weekly shopping list</h2><div className="shopping"><b>🥩 Proteins</b><p>Chicken breast · salmon · white fish · tuna · chicken liver · eggs</p><b>🥬 Vegetables & salad</b><p>Cucumber · tomato · lettuce · spinach · cabbage · broccoli · cauliflower · peppers · onions · herbs</p><b>🍓 Fruits</b><p>Strawberries · blueberries · apple · pear · kiwi · orange</p><b>🥜 Nuts & seeds</b><p>Almonds · walnuts · cashews · pistachios · sunflower seeds · chia</p><b>🍋 Dressings & pantry</b><p>Lemon/lime · olive oil · sumac · oregano · cumin · sesame oil · vinegar · spices</p></div></section>
 :tab==='telegram'?<TelegramPanel/>:<section className="panel"><div className="sectionHead"><div><span className="eyebrow">TODAY'S MEALS</span><h2>Tuesday meal timeline</h2></div></div>{['Curd + berries + seeds','Avocado Nuts Shake','Salmon + lentils + Greek Salad','Apple + walnuts','White Fish + vegetables'].map((m,i)=><div className="meal" key={m}><img src={i===2?saladRecipes[1].image:saladRecipes[0].image} alt=""/><div><span className="eyebrow">{['BREAKFAST','MID-MORNING','LUNCH','EVENING SNACK','DINNER'][i]}</span><h3>{m}</h3><p>{i===2?'Includes the detailed Greek Salad recipe →':'Complete ingredients and recipe available in the meal plan.'}</p></div><span className="arrow">→</span></div>)}<div className="saladCallout"><div className="emoji">🥗</div><div><b>Need a salad?</b><p>Choose from 7 detailed international salad recipes.</p></div><button onClick={()=>setTab('salads')}>Open Salads</button></div></section>}
 <nav><button className={tab==='today'?'navActive':''} onClick={()=>setTab('today')}>⌂<span>Today</span></button><button className={tab==='plan'?'navActive':''} onClick={()=>setTab('plan')}>▦<span>Plan</span></button><button onClick={()=>setTab('salads')} className={tab==='salads'?'navActive':''}>🥗<span>Salads</span></button><button onClick={()=>setTab('shopping')} className={tab==='shopping'?'navActive':''}>🛒<span>Shopping</span></button><button onClick={()=>setTab('telegram')} className={tab==='telegram'?'navActive':''}>✈️<span>Telegram</span></button></nav>
 </main>
}
