export type Recipe={id:string;name:string;category:string;time:string;calories:number;protein:number;carbs:number;fat:number;fiber:number;image:string;ingredients:string[];steps:string[];tip?:string};

export const saladRecipes:Recipe[]=[
{id:'mediterranean',name:'Mediterranean Salad',category:'Salads',time:'10 min',calories:135,protein:3,carbs:12,fat:9,fiber:4,image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85',ingredients:['Cucumber — 100 g','Tomato — 80 g','Lettuce — 50 g','Red onion — 20 g','Parsley — 10 g','Olives — 15 g','Extra-virgin olive oil — 1 tsp (5 ml)','Lemon juice — 1 tbsp','Black pepper — to taste'],steps:['Wash and dry all vegetables thoroughly.','Dice cucumber and tomato; slice onion thinly.','Tear lettuce into bite-size pieces and chop parsley.','Combine vegetables, parsley and olives in a bowl.','Whisk lemon juice, olive oil and black pepper.','Pour dressing over the salad and toss gently just before serving.'],tip:'Keep the dressing separate if preparing in advance.'},
{id:'greek',name:'Greek Salad',category:'Salads',time:'10 min',calories:175,protein:6,carbs:11,fat:12,fiber:4,image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=85',ingredients:['Cucumber — 100 g','Tomato — 100 g','Bell pepper — 50 g','Lettuce — 60 g','Red onion — 20 g','Feta — 25–30 g','Olives — 15 g','Olive oil — 1 tsp (5 ml)','Lemon juice — 1 tbsp','Oregano — ¼ tsp'],steps:['Chop cucumber, tomato and bell pepper.','Slice onion and shred lettuce.','Add vegetables, olives and crumbled feta to a bowl.','Mix lemon juice, olive oil and oregano.','Dress immediately before eating and toss lightly.'],tip:'Choose a modest feta portion to keep calories and sodium controlled.'},
{id:'mexican',name:'Mexican Avocado Salad',category:'Salads',time:'12 min',calories:180,protein:4,carbs:15,fat:12,fiber:6,image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',ingredients:['Lettuce — 80 g','Cucumber — 80 g','Tomato — 80 g','Bell pepper — 60 g','Avocado — 30 g','Red onion — 20 g','Coriander — 10 g','Lime juice — 1 tbsp','Olive oil — 1 tsp','Cumin — ¼ tsp','Chilli powder — a pinch'],steps:['Chop lettuce, cucumber, tomato and bell pepper.','Dice avocado and onion.','Combine vegetables and coriander.','Whisk lime juice, olive oil, cumin and chilli.','Add dressing and toss gently so the avocado stays intact.'],tip:'Do not add sweet chilli sauce or sugar-based dressing.'},
{id:'turkish',name:'Turkish Shepherd Salad',category:'Salads',time:'10 min',calories:120,protein:3,carbs:12,fat:7,fiber:4,image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',ingredients:['Tomato — 100 g','Cucumber — 100 g','Green pepper — 50 g','Red onion — 20 g','Parsley — 10 g','Lemon juice — 1 tbsp','Olive oil — 1 tsp','Sumac — ½ tsp','Black pepper — to taste'],steps:['Dice tomato and cucumber into small pieces.','Finely chop green pepper, onion and parsley.','Combine everything in a bowl.','Add lemon juice, olive oil, sumac and pepper.','Toss and serve fresh.'],tip:'Use plenty of herbs and lemon for flavor without extra sauces.'},
{id:'lebanese',name:'Lebanese Herb Salad',category:'Salads',time:'12 min',calories:105,protein:3,carbs:13,fat:5,fiber:5,image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',ingredients:['Lettuce — 60 g','Cucumber — 80 g','Tomato — 80 g','Radish — 50 g','Parsley — 15 g','Mint — 10 g','Lemon juice — 1 tbsp','Sumac — ½ tsp','Olive oil — 1 tsp'],steps:['Wash and dry the herbs and vegetables.','Slice radish and cucumber; dice tomato.','Chop parsley and mint finely.','Combine all ingredients.','Add lemon, sumac and olive oil.','Toss just before serving.'],tip:'Skip pita/croutons if keeping the meal carbohydrate-controlled.'},
{id:'thai',name:'Thai-Style Crunchy Salad',category:'Salads',time:'15 min',calories:165,protein:5,carbs:14,fat:10,fiber:5,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85',ingredients:['Cabbage — 100 g','Cucumber — 80 g','Lettuce — 60 g','Coriander — 10 g','Mint — 5 g','Crushed peanuts — 10 g','Lime juice — 1 tbsp','Sesame oil — 1 tsp','Fish sauce — 1 tsp','Fresh ginger — ½ tsp','Garlic — 1 small clove','Fresh chilli — optional'],steps:['Finely shred cabbage and slice cucumber.','Tear lettuce and chop herbs.','Mix lime juice, sesame oil, fish sauce, ginger and garlic.','Combine vegetables and herbs.','Add peanuts.','Toss with dressing immediately before serving.'],tip:'Use fish sauce sparingly and avoid sweet chilli sauce.'},
{id:'tuna',name:'Mediterranean Tuna Salad',category:'Salads',time:'12 min',calories:255,protein:29,carbs:12,fat:11,fiber:4,image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85',ingredients:['Tuna in water, drained — 120 g','Lettuce — 70 g','Cucumber — 80 g','Tomato — 80 g','Bell pepper — 50 g','Olives — 10 g','Parsley — 10 g','Lemon juice — 1 tbsp','Olive oil — 1 tsp'],steps:['Drain tuna well.','Chop vegetables and parsley.','Add tuna and olives to the vegetables.','Mix lemon juice and olive oil.','Dress and toss gently.'],tip:'Choose tuna packed in water and check sodium if needed.'}
];

export const dailyMeals=[
['Monday','1 egg + avocado vegetable breakfast','Avocado Nuts Shake','Grilled Chicken + Quinoa + Mediterranean Salad','Strawberries + almonds','Grilled Salmon + vegetables'],
['Tuesday','Curd + berries + seeds','Avocado Nuts Shake','Salmon + lentils + Greek Salad','Apple + walnuts','White Fish + vegetables'],
['Wednesday','Moong Dal Chilla + curd','Avocado Nuts Shake','Chicken + rice + Mexican Salad','Pear + almonds','Salmon + vegetables'],
['Thursday','Besan Chilla + curd','Avocado Nuts Shake','Chicken Liver + chicken + chickpeas + Turkish Salad','Kiwi + almonds','Salmon + vegetables'],
['Friday','Egg + mushroom spinach breakfast','Avocado Nuts Shake','Chicken + barley + Lebanese Salad','Apple + walnuts','Salmon + cabbage salad'],
['Saturday','Low-fat paneer + vegetables','Avocado Nuts Shake','Chicken + sweet potato + Thai Salad','Orange + almonds','Chicken + vegetables'],
['Sunday','Egg + avocado mushroom breakfast','Avocado Nuts Shake','Tuna + chicken + buckwheat + Mediterranean Salad','Strawberries + almonds','White Fish + vegetables']
].map((x,i)=>({day:x[0],meals:x.slice(1),id:i}));

export function getSaladIngredients(){return saladRecipes.flatMap(r=>r.ingredients);}
