export type Recipe={id:string;name:string;category:string;time:string;calories:number;protein:number;carbs:number;fat:number;fiber:number;image:string;ingredients:string[];steps:string[];tip?:string};

export const recipes:Recipe[]=[
{id:'omelette',name:'Egg, Spinach & Avocado',category:'Breakfast',time:'12 min',calories:320,protein:25,carbs:8,fat:20,fiber:6,image:'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1000&q=85',ingredients:['1 egg','Spinach — 50 g','Tomato — 50 g','Mushroom — 60 g','Avocado — 70 g','Olive oil — 1 tsp','Black pepper and herbs'],steps:['Wash and chop the vegetables.','Cook spinach, tomato and mushroom in measured oil.','Add beaten egg and cook gently until set.','Serve with sliced avocado and herbs.'],tip:'Keep the avocado portion measured because it is nutrient-dense.'},
{id:'shake',name:'Avocado Nut & Seed Shake',category:'Mid-morning',time:'5 min',calories:390,protein:15,carbs:12,fat:31,fiber:8,image:'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=1000&q=85',ingredients:['Unsweetened soy milk — 200 ml','Avocado — 70 g','Almonds — 5 g','Walnuts — 5 g','Cashews — 5 g','Pistachios — 5 g','Sunflower seeds — 5 g','Chia seeds — 5 g','Cinnamon — ¼ tsp','Ice'],steps:['Add soy milk and avocado to a blender.','Add the measured nuts, seeds and cinnamon.','Blend until smooth; add ice for texture.','Serve immediately without sugar, honey, dates or syrup.'],tip:'Raw nuts are fine; soaking is optional and does not need to be done for nutrition.'},
{id:'chicken-quinoa',name:'Grilled Chicken + Quinoa + Bhendi',category:'Lunch',time:'25 min',calories:480,protein:40,carbs:35,fat:18,fiber:10,image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1000&q=85',ingredients:['Chicken breast — 180 g','Quinoa cooked — 90 g','Bhendi/okra — 150 g','Broccoli — 100 g','Olive oil — 2 tsp','Garlic, cumin, paprika and lemon'],steps:['Season chicken with lemon, garlic and spices.','Grill chicken until fully cooked.','Steam or sauté okra and broccoli using measured oil.','Serve with the cooked quinoa and vegetables.'],tip:'Keep the quinoa portion measured and fill the rest of the plate with non-starchy vegetables.'},
{id:'salmon-sorakai',name:'Salmon + Sorakai + Spinach',category:'Dinner',time:'25 min',calories:420,protein:35,carbs:15,fat:22,fiber:8,image:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1000&q=85',ingredients:['Salmon — 180 g','Sorakai/bottle gourd — 200 g','Spinach — 100 g','Cucumber — 80 g','Olive oil — 1 tsp','Lemon, garlic and pepper'],steps:['Season salmon with lemon, garlic and pepper.','Pan-sear or bake until fully cooked.','Cook bottle gourd until tender with minimal oil.','Wilt spinach briefly and serve with cucumber salad.'],tip:'Salmon is the fish used in this plan; avoid sugary marinades.'},
{id:'liver',name:'Chicken Liver + Karela + Green Moong',category:'Dinner option',time:'25 min',calories:390,protein:32,carbs:18,fat:18,fiber:9,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85',ingredients:['Chicken liver — 120 g','Karela/bitter gourd — 150 g','Cooked whole green moong — 70–80 g','Tomato — 50 g','Onion — 20 g','Spinach — 75 g','Garlic — 5 g','Olive oil — 1 tsp','Cumin, turmeric and chilli'],steps:['Wash and prepare the karela and vegetables.','Sauté garlic, cumin and onion in measured oil.','Add tomato, spices and liver; cook thoroughly.','Add karela and spinach and cook until tender.','Serve with the measured green moong.'],tip:'Keep chicken liver as a separate meal; do not combine it with chicken breast in the same meal.'},
{id:'barley-chicken',name:'Chicken + Barley + Lebanese Salad',category:'Lunch',time:'25 min',calories:460,protein:38,carbs:33,fat:16,fiber:9,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85',ingredients:['Chicken breast — 180 g','Barley cooked — 90 g','Lettuce — 60 g','Cucumber — 80 g','Tomato — 80 g','Parsley and mint','Olive oil — 1 tsp','Lemon and sumac'],steps:['Season and grill the chicken.','Prepare the cooked barley.','Chop the salad vegetables and herbs.','Dress with lemon, sumac and measured olive oil.','Serve together with the barley portion.']}
];

export const saladRecipes:Recipe[]=[
{id:'mediterranean',name:'Mediterranean Salad',category:'Salads',time:'10 min',calories:135,protein:3,carbs:12,fat:9,fiber:4,image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85',ingredients:['Cucumber — 100 g','Tomato — 80 g','Lettuce — 50 g','Red onion — 20 g','Parsley — 10 g','Olives — 15 g','Extra-virgin olive oil — 1 tsp (5 ml)','Lemon juice — 1 tbsp','Black pepper'],steps:['Wash and dry vegetables.','Dice cucumber and tomato; slice onion.','Tear lettuce and chop parsley.','Combine vegetables, herbs and olives.','Whisk lemon juice, olive oil and pepper.','Dress just before serving.']},
{id:'greek',name:'Greek Salad',category:'Salads',time:'10 min',calories:175,protein:6,carbs:11,fat:12,fiber:4,image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=85',ingredients:['Cucumber — 100 g','Tomato — 100 g','Bell pepper — 50 g','Lettuce — 60 g','Red onion — 20 g','Feta — 25 g','Olives — 15 g','Olive oil — 1 tsp','Lemon and oregano'],steps:['Chop cucumber, tomato and pepper.','Slice onion and shred lettuce.','Add olives and feta.','Mix lemon, oil and oregano.','Dress immediately before eating.']},
{id:'mexican',name:'Mexican Avocado Salad',category:'Salads',time:'12 min',calories:180,protein:4,carbs:15,fat:12,fiber:6,image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',ingredients:['Lettuce — 80 g','Cucumber — 80 g','Tomato — 80 g','Bell pepper — 60 g','Avocado — 30 g','Red onion — 20 g','Coriander — 10 g','Lime juice — 1 tbsp','Olive oil — 1 tsp','Cumin and chilli'],steps:['Chop the vegetables.','Dice avocado and onion.','Combine with coriander.','Whisk lime, oil, cumin and chilli.','Toss gently.'],tip:'No sweet chilli sauce or added sugar.'},
{id:'turkish',name:'Turkish Shepherd Salad',category:'Salads',time:'10 min',calories:120,protein:3,carbs:12,fat:7,fiber:4,image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',ingredients:['Tomato — 100 g','Cucumber — 100 g','Green pepper — 50 g','Red onion — 20 g','Parsley — 10 g','Lemon — 1 tbsp','Olive oil — 1 tsp','Sumac'],steps:['Dice tomato and cucumber.','Chop pepper, onion and parsley.','Combine all vegetables.','Add lemon, oil and sumac.','Toss and serve fresh.']},
{id:'lebanese',name:'Lebanese Herb Salad',category:'Salads',time:'12 min',calories:105,protein:3,carbs:13,fat:5,fiber:5,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85',ingredients:['Lettuce — 60 g','Cucumber — 80 g','Tomato — 80 g','Radish — 50 g','Parsley — 15 g','Mint — 10 g','Lemon — 1 tbsp','Sumac','Olive oil — 1 tsp'],steps:['Wash and dry herbs and vegetables.','Slice radish and cucumber; dice tomato.','Chop herbs finely.','Combine all ingredients.','Add lemon, sumac and oil.','Toss just before serving.'],tip:'Skip pita or croutons when keeping the meal carbohydrate-controlled.'},
{id:'thai',name:'Thai-Style Crunchy Salad',category:'Salads',time:'15 min',calories:165,protein:5,carbs:14,fat:10,fiber:5,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85',ingredients:['Cabbage — 100 g','Cucumber — 80 g','Lettuce — 60 g','Coriander — 10 g','Mint — 5 g','Crushed peanuts — 10 g','Lime juice — 1 tbsp','Sesame oil — 1 tsp','Ginger and garlic','Fresh chilli — optional'],steps:['Shred cabbage and slice cucumber.','Tear lettuce and chop herbs.','Mix lime, sesame oil, ginger and garlic.','Combine vegetables and herbs.','Add peanuts and toss.'],tip:'Avoid sweet chilli sauce and added sugar.'}
];

export const vegetables=[
{name:'Karela',local:'Bitter gourd',image:'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=500&q=85'},
{name:'Thotakura',local:'Amaranth leaves',image:'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=500&q=85'},
{name:'Gongura',local:'Sorrel leaves',image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=500&q=85'},
{name:'Sorakai',local:'Bottle gourd',image:'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&w=500&q=85'},
{name:'Bhendi',local:'Okra',image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=85'},
{name:'Beans',local:'Green beans',image:'https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?auto=format&fit=crop&w=500&q=85'},
{name:'Palak',local:'Spinach',image:'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=500&q=85'},
{name:'Methi',local:'Fenugreek leaves',image:'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=500&q=85'},
{name:'Cabbage',local:'Green cabbage',image:'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=500&q=85'},
{name:'Cauliflower',local:'Cauliflower',image:'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=500&q=85'},
{name:'Capsicum',local:'Bell pepper',image:'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=500&q=85'},
{name:'Brinjal',local:'Eggplant',image:'https://images.unsplash.com/photo-1615484477778-ca3b77940c25?auto=format&fit=crop&w=500&q=85'},
{name:'Dondakaya',local:'Tindora',image:'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=500&q=85'},
{name:'Beerakaya',local:'Ridge gourd',image:'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&w=500&q=85'},
{name:'Pumpkin',local:'Pumpkin',image:'https://images.unsplash.com/photo-1506917728037-b6af01a7d403?auto=format&fit=crop&w=500&q=85'},
{name:'Carrot',local:'Carrot',image:'https://images.unsplash.com/photo-1445282768818-728615cc910a?auto=format&fit=crop&w=500&q=85'}
];

export const dailyMeals=[
{day:'Monday',meals:['Egg + avocado vegetable breakfast','Avocado Nut & Seed Shake','Grilled Chicken + Quinoa + Mediterranean Salad','Strawberries + almonds','Grilled Salmon + vegetables']},
{day:'Tuesday',meals:['Curd + berries + seeds','Avocado Nut & Seed Shake','Salmon + Green Moong + Greek Salad','Apple + walnuts','Salmon + cabbage + cucumber']},
{day:'Wednesday',meals:['Moong Dal Chilla + curd','Avocado Nut & Seed Shake','Chicken + rice + Mexican Salad','Pear + almonds','Grilled Salmon + vegetables']},
{day:'Thursday',meals:['Besan Chilla + curd','Avocado Nut & Seed Shake','Chicken Liver + Karela + Green Moong','Kiwi + almonds','Grilled Salmon + vegetables']},
{day:'Friday',meals:['Egg + mushroom spinach breakfast','Avocado Nut & Seed Shake','Chicken + Barley + Lebanese Salad','Apple + walnuts','Grilled Salmon + cabbage salad']},
{day:'Saturday',meals:['Low-fat paneer + vegetables','Avocado Nut & Seed Shake','Chicken + Barley + Thai Salad','Orange + almonds','Grilled Salmon + vegetables']},
{day:'Sunday',meals:['Egg + avocado mushroom breakfast','Avocado Nut & Seed Shake','Salmon + Buckwheat + Mediterranean Salad','Strawberries + almonds','Grilled Salmon + vegetables']}
];

export const shoppingGroups=[
{title:'Proteins',icon:'🥩',items:['Chicken breast — 1.2 kg','Salmon — 1.2 kg','Eggs — 6','Chicken liver — 120 g','Low-fat paneer — 100 g']},
{title:'Vegetables & greens',icon:'🥬',items:['Karela — 300 g','Thotakura — 200 g','Gongura — 150 g','Sorakai — 500 g','Bhendi — 400 g','Beans — 400 g','Spinach — 300 g','Broccoli — 500 g','Cabbage — 1 small']},
{title:'Fruit & berries',icon:'🍓',items:['Strawberries — 400 g','Blueberries — 200 g','Apple — 3','Pear — 2','Kiwi — 2','Orange — 2']},
{title:'Nuts & seeds',icon:'🥜',items:['Almonds — 100 g','Walnuts — 60 g','Cashews — 40 g','Pistachios — 40 g','Sunflower seeds — 40 g','Chia — 40 g']},
{title:'Grains & pantry',icon:'🌾',items:['Quinoa — 90 g cooked portions','Barley — 180 g cooked portions','Brown/basmati rice — controlled portions','Whole green moong','Besan / gram flour','Olive oil, lemon, herbs and spices']}
];
