export type Recipe={id:string;name:string;category:string;time:string;calories:number;protein:number;carbs:number;fat:number;fiber:number;image:string;ingredients:string[];steps:string[];tip?:string};

const img={chicken:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=85',salmon:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=85',eggs:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=85',moong:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85',shake:'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=85',fruit:'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=900&q=85',paneer:'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=900&q=85',grain:'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=900&q=85'};

export const dailyMeals=[
 {day:'Monday',id:0,meals:['Egg, spinach & quinoa breakfast','Avocado and nuts shake','Chicken quinoa bowl','Apple & almonds','Salmon, vegetables & barley']},
 {day:'Tuesday',id:1,meals:['Whole green moong chilla','Avocado and nuts shake','Salmon, moong & okra','Pear & walnuts','Chicken, bottle gourd & buckwheat']},
 {day:'Wednesday',id:2,meals:['Besan vegetable chilla','Avocado and nuts shake','Chicken brown-rice bowl','Orange & almonds','Salmon, greens & quinoa']},
 {day:'Thursday',id:3,meals:['Spinach besan chilla','Avocado and nuts shake','Chicken liver, karela & moong','Strawberries & pistachios','Chicken, thotakura & barley']},
 {day:'Friday',id:4,meals:['Mushroom egg plate','Avocado and nuts shake','Chicken barley bowl','Apple & walnuts','Salmon, cabbage & buckwheat']},
 {day:'Saturday',id:5,meals:['Paneer mushroom bowl','Avocado and nuts shake','Thai-style chicken barley salad','Guava & almonds','Chicken cauliflower quinoa bowl']},
 {day:'Sunday',id:6,meals:['Egg, mushroom & quinoa','Avocado and nuts shake','Salmon buckwheat bowl','Strawberries & walnuts','Salmon, bottle gourd & brown rice']}
];

const mealDetails:Record<string,Partial<Recipe>>={
' Egg, spinach & quinoa breakfast':{},
'Egg, spinach & quinoa breakfast':{category:'Breakfast',time:'20 min',calories:360,protein:19,carbs:29,fat:17,fiber:7,image:img.eggs,ingredients:['1 egg','Spinach — 50 g','Tomato — 50 g','Onion — 20 g','Avocado — 40 g','Quinoa, dry — 30 g','Olive oil — 5 g','Pepper and cumin'],steps:['Rinse quinoa and simmer in water until tender.','Heat the measured oil; soften onion and tomato.','Add spinach, then the beaten egg and cook thoroughly.','Serve with the quinoa and avocado.']},
'Avocado and nuts shake':{category:'Snack',time:'5 min',calories:330,protein:10,carbs:17,fat:26,fiber:8,image:img.shake,ingredients:['Unsweetened soy milk — 200 ml','Avocado — 70 g','Almonds — 5 g','Walnuts — 5 g','Cashews — 5 g','Pistachios — 5 g','Sunflower seeds — 5 g','Chia seeds — 5 g','Cinnamon — ¼ tsp','Ice/water as needed'],steps:['Add all ingredients to a blender.','Blend until smooth; thin with water if desired.','Serve without sugar, honey, dates or syrup.'],tip:'Calorie and carbohydrate values are estimates; check your individual glucose response.'},
'Whole green moong chilla':{category:'Breakfast',time:'25 min + soaking',calories:300,protein:17,carbs:38,fat:8,fiber:10,image:img.moong,ingredients:['Whole green moong, dry — 40 g','Spinach — 40 g','Onion — 20 g','Tomato — 40 g','Plain curd — 100 g','Oil — 5 g','Ginger, cumin and water'],steps:['Soak moong for 6–8 hours, rinse and grind with water.','Mix in chopped vegetables, ginger and cumin.','Cook as small pancakes using the measured oil.','Serve with plain curd.']},
'Besan vegetable chilla':{category:'Breakfast',time:'20 min',calories:290,protein:15,carbs:34,fat:9,fiber:8,image:img.moong,ingredients:['Besan — 40 g','Capsicum — 40 g','Tomato — 40 g','Onion — 20 g','Spinach — 40 g','Plain curd — 100 g','Oil — 5 g','Cumin and turmeric'],steps:['Mix besan with water, spices and chopped vegetables.','Rest the batter for 5 minutes.','Cook as two small pancakes using the measured oil.','Serve with plain curd.']},
'Spinach besan chilla':{category:'Breakfast',time:'20 min',calories:280,protein:14,carbs:32,fat:9,fiber:8,image:img.moong,ingredients:['Besan — 40 g','Spinach — 50 g','Tomato — 40 g','Onion — 20 g','Plain curd — 100 g','Oil — 5 g','Cumin, turmeric and water'],steps:['Mix besan with water, spices and finely chopped vegetables.','Rest for 5 minutes.','Cook as two small pancakes using measured oil.','Serve with curd.']},
'Mushroom egg plate':{category:'Breakfast',time:'20 min',calories:350,protein:20,carbs:28,fat:16,fiber:7,image:img.eggs,ingredients:['1 egg','Mushrooms — 100 g','Spinach — 40 g','Tomato — 50 g','Avocado — 40 g','Barley, dry — 30 g','Oil — 5 g'],steps:['Cook barley in water until tender.','Sauté mushrooms, tomato and spinach in measured oil.','Add egg and cook fully.','Serve with barley and avocado.']},
'Paneer mushroom bowl':{category:'Breakfast',time:'15 min',calories:330,protein:23,carbs:20,fat:17,fiber:6,image:img.paneer,ingredients:['Low-fat paneer — 100 g','Mushrooms — 75 g','Spinach — 50 g','Tomato — 50 g','Cucumber — 100 g','Avocado — 30 g','Oil — 5 g'],steps:['Sauté mushrooms and spinach with measured oil.','Add paneer and cook until hot.','Serve with tomato, cucumber and avocado.']},
'Egg, mushroom & quinoa':{category:'Breakfast',time:'20 min',calories:350,protein:20,carbs:28,fat:16,fiber:7,image:img.eggs,ingredients:['1 egg','Mushrooms — 75 g','Spinach — 40 g','Tomato — 50 g','Cucumber — 100 g','Avocado — 40 g','Quinoa, dry — 30 g','Oil — 5 g'],steps:['Cook quinoa in water until tender.','Sauté mushrooms, spinach and tomato in measured oil.','Add egg and cook fully.','Serve with cucumber and avocado.']},
'Apple & almonds':{category:'Snack',time:'2 min',calories:150,protein:3,carbs:22,fat:6,fiber:5,image:img.fruit,ingredients:['Apple — 150 g edible portion','Almonds — 10 g'],steps:['Wash and slice the apple.','Eat with the measured almonds.']},
'Pear & walnuts':{category:'Snack',time:'2 min',calories:160,protein:2,carbs:23,fat:7,fiber:5,image:img.fruit,ingredients:['Pear — 150 g edible portion','Walnuts — 10 g'],steps:['Wash and slice the pear.','Eat with the measured walnuts.']},
'Orange & almonds':{category:'Snack',time:'2 min',calories:130,protein:3,carbs:19,fat:5,fiber:4,image:img.fruit,ingredients:['Orange — 130 g edible portion','Almonds — 10 g'],steps:['Peel the orange and portion it.','Eat with the measured almonds.']},
'Strawberries & pistachios':{category:'Snack',time:'3 min',calories:120,protein:3,carbs:13,fat:6,fiber:4,image:img.fruit,ingredients:['Strawberries — 150 g','Pistachios — 10 g'],steps:['Rinse strawberries and remove stems.','Serve with the measured pistachios.']},
'Apple & walnuts':{category:'Snack',time:'2 min',calories:160,protein:2,carbs:22,fat:8,fiber:5,image:img.fruit,ingredients:['Apple — 150 g edible portion','Walnuts — 10 g'],steps:['Wash and slice the apple.','Eat with the measured walnuts.']},
'Guava & almonds':{category:'Snack',time:'3 min',calories:140,protein:4,carbs:17,fat:6,fiber:7,image:img.fruit,ingredients:['Guava — 120–150 g edible portion','Almonds — 10 g'],steps:['Wash and slice guava.','Eat with the measured almonds.']},
'Strawberries & walnuts':{category:'Snack',time:'3 min',calories:130,protein:2,carbs:13,fat:8,fiber:4,image:img.fruit,ingredients:['Strawberries — 150 g','Walnuts — 10 g'],steps:['Rinse strawberries and remove stems.','Serve with the measured walnuts.']}
};

const lunchDinner:Record<string,Partial<Recipe>>={
'Chicken quinoa bowl':{category:'Lunch',time:'30 min',calories:520,protein:48,carbs:32,fat:18,fiber:9,image:img.chicken,ingredients:['Raw chicken breast — 200–220 g','Quinoa, dry — 30 g','Broccoli — 150 g','Cucumber — 100 g','Tomato — 80 g','Lettuce — 60 g','Onion — 20 g','Parsley — 10 g','Olives — 15 g','Lemon juice — 15 ml','Olive oil — 10 g','Unsweetened buttermilk — 200 ml'],steps:['Season chicken with lemon, garlic and pepper.','Grill/pan-cook until the centre reaches 74°C.','Cook quinoa and steam broccoli.','Combine salad vegetables and herbs; dress with measured oil and lemon.','Serve with buttermilk.']},
'Salmon, vegetables & barley':{category:'Dinner',time:'30 min',calories:550,protein:42,carbs:31,fat:25,fiber:8,image:img.salmon,ingredients:['Raw salmon — 190–220 g','Barley, dry — 30 g','Zucchini — 100 g','Cauliflower — 100 g','Spinach — 75 g','Cucumber — 100 g','Tomato — 80 g','Oil — 5 g','Buttermilk — 150–200 ml','Lemon, garlic and pepper'],steps:['Season salmon with lemon, garlic and pepper.','Bake at 200°C until it reaches 63°C internally.','Cook barley according to packet directions.','Steam or sauté vegetables using measured oil.','Serve with cucumber-tomato salad and buttermilk.']},
'Salmon, moong & okra':{category:'Lunch',time:'35 min',calories:530,protein:43,carbs:34,fat:21,fiber:10,image:img.salmon,ingredients:['Raw salmon — 180–200 g','Whole green moong, dry — 40 g','Okra — 150 g','Cucumber — 100 g','Tomato — 80 g','Oil — 5 g','Buttermilk — 200 ml','Lemon, garlic and cumin'],steps:['Soak moong, then boil until tender.','Season and bake salmon until it reaches 63°C internally.','Cook okra with garlic, cumin and measured oil.','Serve with cucumber-tomato salad and buttermilk.']},
'Chicken, bottle gourd & buckwheat':{category:'Dinner',time:'35 min',calories:520,protein:48,carbs:31,fat:17,fiber:9,image:img.chicken,ingredients:['Raw chicken breast — 200–220 g','Bottle gourd — 200 g','Spinach — 75 g','Buckwheat, dry — 30 g','Tomato — 50 g','Onion — 20 g','Cucumber — 100 g','Lettuce — 60 g','Oil — 5 g','Buttermilk — 150–200 ml','Ginger, garlic and spices'],steps:['Cook buckwheat separately in water.','Cook onion, tomato, ginger, garlic and chicken until chicken reaches 74°C.','Add bottle gourd and cook until tender; stir in spinach.','Serve with buckwheat, salad and buttermilk.']},
'Chicken brown-rice bowl':{category:'Lunch',time:'30 min',calories:520,protein:48,carbs:33,fat:17,fiber:9,image:img.chicken,ingredients:['Raw chicken breast — 200–220 g','Brown rice, dry — 30–35 g','Broccoli — 150 g','Lettuce — 100 g','Cucumber — 80 g','Tomato — 80 g','Capsicum — 60 g','Avocado — 30 g','Coriander — 10 g','Olive oil — 10 g','Buttermilk — 200 ml','Lime, garlic and paprika'],steps:['Cook brown rice.','Season chicken with lime, garlic and paprika; cook to 74°C internally.','Steam broccoli.','Toss salad vegetables, coriander and avocado with measured oil and lime.','Serve together with buttermilk.']},
'Salmon, greens & quinoa':{category:'Dinner',time:'30 min',calories:550,protein:42,carbs:31,fat:25,fiber:8,image:img.salmon,ingredients:['Raw salmon — 190–220 g','Quinoa, dry — 30 g','Broccoli — 100 g','Zucchini — 100 g','Spinach — 75 g','Cucumber — 100 g','Tomato — 80 g','Oil — 5 g','Buttermilk — 150–200 ml','Lemon, garlic and pepper'],steps:['Bake seasoned salmon until 63°C internally.','Cook quinoa in water.','Steam broccoli and cook zucchini and spinach with measured oil.','Serve with fresh cucumber-tomato salad and buttermilk.']},
'Chicken liver, karela & moong':{category:'Lunch',time:'35 min',calories:450,protein:34,carbs:30,fat:17,fiber:11,image:img.chicken,ingredients:['Raw chicken liver — 120 g','Karela — 150 g','Whole green moong, dry — 30–40 g','Tomato — 50 g','Onion — 20 g','Spinach — 75 g','Oil — 5 g','Buttermilk — 200 ml','Ginger and garlic'],steps:['Soak and boil moong until tender.','Sauté onion, ginger, garlic and karela with measured oil.','Add tomato and liver; cook thoroughly to 74°C internally.','Cook spinach separately and serve with moong and buttermilk.'],tip:'Keep liver occasional because it is very high in preformed vitamin A.'},
'Chicken, thotakura & barley':{category:'Dinner',time:'35 min',calories:520,protein:48,carbs:32,fat:17,fiber:10,image:img.chicken,ingredients:['Raw chicken breast — 200–220 g','Thotakura/amaranth leaves — 100 g','Bottle gourd — 150 g','Barley, dry — 30 g','Tomato — 50 g','Cucumber — 100 g','Lettuce — 60 g','Oil — 5 g','Buttermilk — 150–200 ml','Ginger, garlic and spices'],steps:['Cook barley in water.','Cook chicken with tomato, ginger, garlic and spices until it reaches 74°C.','Add bottle gourd; cook until tender. Stir in washed amaranth leaves.','Serve with barley, salad and buttermilk.']},
'Chicken barley bowl':{category:'Lunch',time:'30 min',calories:520,protein:48,carbs:33,fat:17,fiber:10,image:img.chicken,ingredients:['Raw chicken breast — 200–220 g','Barley, dry — 30–35 g','Broccoli — 150 g','Lettuce — 80 g','Cucumber — 80 g','Tomato — 80 g','Radish — 40 g','Parsley — 10 g','Mint — 5 g','Olive oil — 10 g','Buttermilk — 200 ml','Lemon, garlic and pepper'],steps:['Cook barley in water.','Season and cook chicken to 74°C internally.','Steam broccoli.','Toss salad vegetables and herbs with lemon and measured oil.','Serve together with buttermilk.']},
'Salmon, cabbage & buckwheat':{category:'Dinner',time:'30 min',calories:550,protein:42,carbs:31,fat:25,fiber:8,image:img.salmon,ingredients:['Raw salmon — 190–220 g','Buckwheat, dry — 30 g','Cabbage — 100 g','Zucchini — 100 g','Spinach — 75 g','Cucumber — 100 g','Tomato — 80 g','Oil — 5 g','Buttermilk — 150–200 ml','Lemon, garlic and pepper'],steps:['Bake salmon until 63°C internally.','Cook buckwheat in water.','Steam or sauté cabbage, zucchini and spinach with measured oil.','Serve with salad and buttermilk.']},
'Thai-style chicken barley salad':{category:'Lunch',time:'35 min',calories:530,protein:47,carbs:34,fat:18,fiber:9,image:img.chicken,ingredients:['Raw chicken breast — 200–220 g','Barley, dry — 30–35 g','Cabbage — 100 g','Cucumber — 80 g','Lettuce — 60 g','Green beans — 100 g','Coriander — 10 g','Mint — 5 g','Peanuts — 10 g','Sesame oil — 5 g','Lime, ginger and garlic','Unsweetened buttermilk — 200 ml'],steps:['Cook chicken to 74°C internally and cook barley.','Boil green beans until tender but crisp.','Shred cabbage, cucumber and lettuce; chop herbs.','Mix lime, ginger, garlic and measured sesame oil.','Toss with chicken, vegetables and peanuts. Do not add fish sauce, sugar or sweet chilli sauce.']},
'Chicken cauliflower quinoa bowl':{category:'Dinner',time:'30 min',calories:520,protein:48,carbs:31,fat:17,fiber:9,image:img.chicken,ingredients:['Raw chicken breast — 200–220 g','Cauliflower — 150 g','Zucchini — 100 g','Spinach — 75 g','Quinoa, dry — 30 g','Cucumber — 100 g','Tomato — 80 g','Oil — 5 g','Buttermilk — 150–200 ml','Garlic, lemon and spices'],steps:['Cook quinoa in water.','Season chicken and cook to 74°C internally.','Steam cauliflower; sauté zucchini and spinach with measured oil.','Serve with cucumber-tomato salad and buttermilk.']},
'Salmon buckwheat bowl':{category:'Lunch',time:'30 min',calories:550,protein:42,carbs:31,fat:25,fiber:8,image:img.salmon,ingredients:['Raw salmon — 190–220 g','Buckwheat, dry — 30–35 g','Broccoli — 150 g','Cucumber — 100 g','Tomato — 80 g','Lettuce — 60 g','Onion — 20 g','Parsley — 10 g','Olives — 15 g','Olive oil — 10 g','Buttermilk — 200 ml','Lemon, garlic and pepper'],steps:['Bake salmon until 63°C internally.','Cook buckwheat and steam broccoli.','Make salad from cucumber, tomato, lettuce, onion, parsley and olives.','Dress with measured olive oil and lemon; serve with buttermilk.']},
'Salmon, bottle gourd & brown rice':{category:'Dinner',time:'30 min',calories:550,protein:42,carbs:31,fat:25,fiber:8,image:img.salmon,ingredients:['Raw salmon — 190–220 g','Bottle gourd — 200 g','Spinach — 75 g','Brown rice, dry — 30 g','Cucumber — 100 g','Tomato — 80 g','Oil — 5 g','Buttermilk — 150–200 ml','Ginger, garlic and lemon'],steps:['Cook brown rice in water.','Bake salmon until it reaches 63°C internally.','Cook bottle gourd with ginger and garlic; stir in spinach.','Serve with salad and buttermilk.']}
};

// Add remaining recipe names to a reusable safe preparation template if their name is similar.
function recipeFor(name:string,day:string,index:number):Recipe{
 const detail=mealDetails[name] ?? lunchDinner[name] ?? {};
 let category=detail.category ?? (index===0?'Breakfast':index===1||index===3?'Snack':index===2?'Lunch':'Dinner');
 let image=detail.image ?? (name.toLowerCase().includes('salmon')?img.salmon:name.toLowerCase().includes('chicken')?img.chicken:name.toLowerCase().includes('shake')?img.shake:name.toLowerCase().includes('egg')?img.eggs:img.grain);
 let ingredients=detail.ingredients ?? ['Use the exact foods and portions listed for this meal in the weekly plan.','Use measured oil, herbs and spices; avoid added sugar.'];
 let steps=detail.steps ?? ['Prepare the ingredients listed for this meal.','Cook poultry to 74°C internally or salmon to 63°C internally, where applicable.','Cook grains/pulses in water and measure the serving.','Serve with the planned vegetables/salad and unsweetened buttermilk if listed.'];
 return {id:`${day}-${index}-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name,category,time:detail.time??'20–30 min',calories:detail.calories??300,protein:detail.protein??20,carbs:detail.carbs??25,fat:detail.fat??10,fiber:detail.fiber??6,image,ingredients,steps,tip:detail.tip??'Nutrition figures are estimates, not laboratory values. Check glucose response and confirm the plan with your diabetes clinician/dietitian.'};
}
export function getMealRecipe(name:string,day:string,index:number){return recipeFor(name,day,index)}
export const allMealRecipes:Recipe[]=dailyMeals.flatMap(d=>d.meals.map((name,i)=>recipeFor(name,d.day,i)));

export const weeklyIngredients: Record<string,string[]>={
Monday:['Egg — 1','Avocado — 110 g','Unsweetened soy milk — 200 ml','Almonds — 15 g','Walnuts — 5 g','Cashews — 5 g','Pistachios — 5 g','Sunflower seeds — 5 g','Chia seeds — 5 g','Chicken breast — 200–220 g','Quinoa, dry — 30 g','Broccoli — 150 g','Cucumber — 200 g','Tomato — 210 g','Lettuce — 60 g','Apple — 150 g','Salmon — 190–220 g','Zucchini — 100 g','Spinach — 125 g','Barley, dry — 30 g'],
Tuesday:['Whole green moong, dry — 80 g','Spinach — 115 g','Onion — 40 g','Tomato — 170 g','Plain curd — 100 g','Unsweetened soy milk — 200 ml','Avocado — 70 g','Salmon — 180–200 g','Okra — 150 g','Cucumber — 200 g','Pear — 150 g','Walnuts — 15 g','Chicken breast — 200–220 g','Bottle gourd — 200 g','Buckwheat, dry — 30 g','Lettuce — 60 g'],
Wednesday:['Besan — 40 g','Capsicum — 100 g','Tomato — 200 g','Onion — 20 g','Spinach — 115 g','Plain curd — 100 g','Unsweetened soy milk — 200 ml','Avocado — 100 g','Chicken breast — 200–220 g','Brown rice, dry — 30–35 g','Broccoli — 250 g','Cucumber — 180 g','Lettuce — 100 g','Orange — 130 g','Almonds — 15 g','Salmon — 190–220 g','Zucchini — 100 g','Quinoa, dry — 30 g'],
Thursday:['Besan — 40 g','Spinach — 125 g','Tomato — 140 g','Onion — 40 g','Plain curd — 100 g','Unsweetened soy milk — 200 ml','Avocado — 70 g','Chicken liver — 120 g','Karela — 150 g','Whole green moong, dry — 30–40 g','Thotakura — 100 g','Bottle gourd — 150 g','Barley, dry — 30 g','Strawberries — 150 g','Pistachios — 15 g','Chicken breast — 200–220 g','Cucumber — 100 g','Lettuce — 60 g'],
Friday:['Egg — 1','Mushrooms — 100 g','Spinach — 115 g','Tomato — 210 g','Avocado — 110 g','Barley, dry — 30–35 g','Unsweetened soy milk — 200 ml','Chicken breast — 200–220 g','Broccoli — 150 g','Lettuce — 80 g','Cucumber — 180 g','Radish — 40 g','Parsley — 10 g','Mint — 5 g','Apple — 150 g','Walnuts — 15 g','Salmon — 190–220 g','Buckwheat, dry — 30 g','Cabbage — 100 g','Zucchini — 100 g'],
Saturday:['Paneer — 100 g','Mushrooms — 75 g','Spinach — 125 g','Tomato — 130 g','Cucumber — 280 g','Avocado — 100 g','Unsweetened soy milk — 200 ml','Chicken breast — 400–440 g','Barley, dry — 30–35 g','Cabbage — 100 g','Lettuce — 60 g','Green beans — 100 g','Coriander — 10 g','Mint — 5 g','Peanuts — 10 g','Guava — 120–150 g','Almonds — 15 g','Cauliflower — 150 g','Zucchini — 100 g','Quinoa, dry — 30 g'],
Sunday:['Egg — 1','Mushrooms — 75 g','Spinach — 115 g','Tomato — 210 g','Cucumber — 200 g','Avocado — 110 g','Quinoa, dry — 30 g','Unsweetened soy milk — 200 ml','Salmon — 380–440 g','Buckwheat, dry — 30–35 g','Broccoli — 150 g','Lettuce — 60 g','Onion — 20 g','Parsley — 10 g','Olives — 15 g','Strawberries — 150 g','Walnuts — 10 g','Bottle gourd — 200 g','Brown rice, dry — 30 g']
};

export const workoutPlan=[
 {day:'Monday',focus:'Abs + core foundation',duration:'20 min',moves:[['Dead bug','3 × 10 each side','Keep lower back gently pressed down.'],['Forearm plank','3 × 20–30 sec','Keep body in a straight line; breathe normally.'],['Reverse crunch','3 × 10–12','Curl pelvis gently; avoid swinging.'],['Bird dog','2 × 10 each side','Move slowly and keep hips level.']]},
 {day:'Tuesday',focus:'Strength + light core',duration:'25 min',moves:[['Bodyweight squat','3 × 12','Sit hips back; keep knees aligned with toes.'],['Incline push-up','3 × 8–12','Use a stable counter or bench.'],['Glute bridge','3 × 12','Squeeze glutes without arching lower back.'],['Side plank (knees bent)','2 × 20 sec each side','Stop if you feel back or shoulder pain.']]},
 {day:'Wednesday',focus:'Six-pack core',duration:'20 min',moves:[['Heel taps','3 × 12 each side','Lift shoulders slightly; move with control.'],['Dead bug','3 × 10 each side','Keep torso stable.'],['Knee tuck','3 × 10','Use a chair or floor version that feels comfortable.'],['Forearm plank','3 × 20–35 sec','Keep breathing; do not hold your breath.']]},
 {day:'Thursday',focus:'Recovery + mobility',duration:'20 min',moves:[['Easy walk','12 min','Comfortable pace; check glucose as advised.'],['Cat-cow','2 × 8','Move gently through a comfortable range.'],['Hip-flexor stretch','2 × 25 sec each side','No bouncing.'],['Thoracic rotation','2 × 8 each side','Move slowly.']]},
 {day:'Friday',focus:'Abs + full body',duration:'25 min',moves:[['Bird dog','3 × 10 each side','Keep hips level.'],['Reverse crunch','3 × 10–12','Use a slow, controlled motion.'],['Incline push-up','3 × 8–12','Use a stable surface.'],['Bodyweight squat','3 × 12','Stop if dizzy or unwell.'],['Side plank (knees bent)','2 × 20 sec each side','Keep shoulder stacked over elbow.']]},
 {day:'Saturday',focus:'Core endurance + walking',duration:'25 min',moves:[['Easy-to-brisk walk','15 min','Choose a pace where you can still speak.'],['Heel taps','2 × 12 each side','Controlled movement.'],['Dead bug','2 × 10 each side','Keep back comfortable.'],['Forearm plank','3 × 20–30 sec','Modify by placing knees down.']]},
 {day:'Sunday',focus:'Rest / gentle mobility',duration:'10–15 min',moves:[['Gentle walk','5–10 min','Optional; easy pace.'],['Full-body mobility','5 min','Gentle, pain-free range of motion.']]}
];

export function getShoppingDepartments(day:string){
 const items=weeklyIngredients[day]??[];
 const groups:{title:string;items:string[]}[]=[{title:'🥩 Protein & dairy',items:[]},{title:'🥬 Vegetables & herbs',items:[]},{title:'🍎 Fruit',items:[]},{title:'🌾 Grains & pulses',items:[]},{title:'🥜 Nuts & seeds',items:[]},{title:'🧂 Pantry & seasoning',items:[]}];
 for(const item of items){const s=item.toLowerCase();let i=5;if(/chicken|salmon|egg|paneer|curd|buttermilk|soy milk|liver/.test(s))i=0;else if(/spinach|tomato|onion|broccoli|cucumber|lettuce|zucchini|cauliflower|cabbage|bottle gourd|karela|okra|thotakura|mushroom|capsicum|radish|parsley|mint|coriander|green beans/.test(s))i=1;else if(/apple|pear|orange|strawberr|guava|avocado/.test(s))i=2;else if(/quinoa|barley|buckwheat|rice|moong|besan/.test(s))i=3;else if(/almond|walnut|cashew|pistachio|sunflower|chia|peanut|olive/.test(s))i=4;groups[i].items.push(item)}
 return groups.filter(g=>g.items.length);
}
